libmozevent/mercurial.py
This warning is useless as it covers a know step in the workflow and we have a dedicated fallback from TC secret.
=> mercurial: Downgrade log level when a base revision is not available

libmozevent/phabricator.py
It's only used by risk analysis trigger for now.
We could support later group reviewers if needed
=> Avoid loading group reviewers

libmozevent/taskcluster.py
=> Use Taskcluster local configuration 

libmozevent/pulse.py
We don't need to be so reactive.
=> Check if the connection is alive every 7 seconds instead of all the time

libmozevent/mercurial.py, tests/test_mercurial.py
This is needed for https://github.com/mozilla/code-review/pull/264.
=> Send the revision too along with the Treeherder URL when a try push is done

libmozevent/pulse.py
=> Support listening on multiple queues and routes on the same pulse connection

libmozevent/pulse.py
This is needed to connect to the "communitytc" virtual host, but it is not working yet. I think the pulse user needs some permissions to connect to the virtual host.
=>  Support connecting to an AMQP virtual host 

libmozevent/bus.py
Initially I wanted to lower the level to DEBUG, but then I thought this is not so useful, so better to just stop logging.
=> Don't log whenever we put a message in a queue

libmozevent/monitoring.py, tests/conftest.py, tests/test_monitoring.py
=> monitoring: Use Taskcluster instance url in emails

requirements.txt
@La0 could you test this on your machine too?
If I don't do this, on my machine pulse fails with `TypeError: cannot use a bytes pattern on a string-like object`.
=> Require at least aioamqp 0.13.0

libmozevent/bus.py, libmozevent/storage.py, libmozevent/utils.py, tests/test_storage.py
When Redis is not available, the data is simply stored in a dict (so it is lost on restart). When Redis is available, it is stored there.
When an object of the class is created, the whole data is loaded in memory for performance reasons (we need to access it very quickly), so this class is only useful for small data (e.g. our needs for tracking bugbug stuff or for monitoring tasks). I've called it EphemeralStorage and made the expiration a compulsory argument to make it clear that it can't be used as a database.
The data is stored this way:
- Each key/value is stored as a Redis string with a given expiration;
- Each key is added to a Sorted Set, with the expiration time being the score in the set (this way we can easily and quickly remove expired keys and retrieve non-expired keys from …
=> Add a module to store data in a temporary fashion

libmozevent/phabricator.py
I couldn't find any usage of it in this file or in code-review.
=> Remove PhabricatorPatch tuple as it is not used (and already defined in libmozdata)

libmozevent/storage.py, tests/test_storage.py
With the previous implementation, since the cache was in local memory, separate workers could not access to the same values.
=> Simplify EphemeralStorage, make it work across separate workers

requirements.txt
Don't rely on it to be indirectly installed via the Taskcluster dependency
=> List aiohttp in the requirements

.isort.cfg, libmozevent/bus.py, libmozevent/mercurial.py, libmozevent/monitoring.py, libmozevent/phabricator.py, libmozevent/pulse.py, tests/conftest.py, tests/test_bus.py, tests/test_mercurial.py, tests/test_phabricator.py
Using tenacity would require a large refactoring, as the method is not retried in a direct loop, but through the usage of the libmozvent queues.
Fixes https://github.com/mozilla/code-review/issues/328
=> phabricator: Use an exponential backoff sleep time

libmozevent/utils.py
Removing the need for an explicit retry function since it can be added via importing tenacity or any other library
=> utils: Remove the implementation of the retry function

libmozevent/bus.py, libmozevent/storage.py
Changing from default protocol to highest protocol while dumping data using pickle.
Issue ref: https://github.com/mozilla/libmozevent/issues/51
=> Use HIGHEST Pickle protocol for storage and bus

libmozevent/mercurial.py, tests/conftest.py
This should fix the issues that we've seen on Heroku where the connetion to `hg` was lost thus making all our jobs to fail.
=> For Mercurial integration, re-open connection if this is None.

libmozevent/mercurial.py
Also verify if the repo is dirty or not, and if so print out the files that have been touched. `hg status` has been used as implemented by [hglib](https://www.mercurial-scm.org/repo/python-hglib/file/tip/hglib/client.py#l1461).
=> mercurial: do not use `hg identify` where it's not needed.

libmozevent/bus.py, libmozevent/storage.py, libmozevent/utils.py, requirements.txt
- Upgrade to aioredis 2.0.0
- as talked with @marco-c it's a good idea to cache the connection and to use a connection pool with auto-reconnect. The connection is cached as a static member field
=> utils: AsyncRedis refactoring and aioredis upgrade to 2.0.0

libmozevent/mercurial.py, libmozevent/phabricator.py
References https://github.com/mozilla/code-review/issues/102
This new attribute is needed to determine whether to alert (via Phabricator) that the base revision changed for a patch analyzed by the `code-review-bot` or not.
@abpostelnicu We will need a new release of `libmozevent` to finish this work on `code-review-bot`.
=> Add a missing_base_revision boolean to PhabricatorBuild

libmozevent/bus.py, libmozevent/utils.py, tests/test_utils.py
Related to https://github.com/mozilla/code-review/issues/1267
Simpler approach than [using a WorkerMixin](!77)
=> Allow to restore bus messages for sequential tasks

.taskcluster.yml
Starting with newer base docker images, 3.11+ aioredis is not compatible. More than this `rs_parsepatch` needs to be built so we would need to ship in the docker image rust/cargo.
=> Limit base docker image to python 3.10

.pre-commit-config.yaml
Since flake8 moved away from gitlab we should do the same or else our pre-commit infra is dead.
=> Move flake8 from gitlab to github

.pre-commit-config.yaml
To fix this error
```
/root/.cache/pre-commit/repos708qki0/py_env-python3/lib/python3.10/site-packages/redis-stubs/cluster.pyi:253: error:(B Positional-only parameters are only supported in Python 3.8 and greater(B
Found 1 error in 1 file (errors prevented further checking)(B
```
in pre-commit
=> Bump mypy in CI

libmozevent/phabricator.py
Fixes #93
We were previously waiting:
2^0 * 10 = 10s
2^1 * 10 = 20s
2^2 * 10 = 40s
2^3 * 10 = 80s
2^4 * 10 = 160s
for a total of 310 seconds (slightly more than 5 minutes)
We are now going to wait:
2^0 * 15 = 15s
2^1 * 15 = 30s
2^2 * 15 = 60s
2^3 * 15 = 120s
2^4 * 15 = 240s
2^5 * 15 = 480s
for a total of 945 seconds (almost 16 minutes)
=> phabricator: Retry up to 6 times, with 15 s wait
